version: '3'

services:
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: thinking-machines-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  api:
    build:
      context: ./video-server/api
    image: api:1.0.0
    volumes:
      - ./microservices/api:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./microservices/frontend
    image: frontend:1.0.0
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./microservices/frontend:/app:rw

volumes:
  db-data:
